---                                                                                                                                                                  
layout: post                                                                                                                                                         
title: "Bilans des simulations de fin de championnat 2013/2014"                                                                                                                                                        
category: posts                                                                                                                                                      
---  


```{r knitr_init, echo=FALSE, results="asis", cache=FALSE}
library(knitr)

## Global options
options(scipen=10000)
options(max.print="70")
options(prompt="R> ")
opts_chunk$set(fig.path="images/2014-05-23-bilan-simulations-2014/",
               opts_chunk$set(fig.cap = "center"),
               echo=FALSE,
               cache.path="cache/",
               cache=FALSE,
               prompt=TRUE,
               tidy=TRUE,
               highlight=TRUE,
               comment=NA,
               message=TRUE,
               warning=TRUE,
               background=".95;.95;.95",
               out.format="jekyll",
               dev="png",
               fig.width=9,
               fig.height=7)
opts_knit$set(width=75)
opts_knit$set(base.url="/")
options(knitr.table.format = 'html')
```

```{r load, echo=FALSE, results="hide", cache=FALSE, message=FALSE}
library(dplyr)
library(XML)
library(data.table)
library(reshape2)
library(ggplot2)

## Chargement des données des simulations

rdata_files <- list.files(path="src/shiny/app/www/data/Ligue_1/2013-2014", pattern="*.Rdata", full.names=TRUE)
journees <- gsub('^.*2013-2014/(\\d+?)_probas.*$', '\\1', rdata_files)
typesim <- gsub('^.*2013-2014/\\d+?_probas_(.*?)\\.Rdata.*$', '\\1', rdata_files)

d <- data.frame(journee=numeric(), typesim=character(), eq=character(), classement=numeric(), n =numeric(), prob=character())

for (i in 1:length(rdata_files)) {
    load(rdata_files[i])
    tab$journee <- journees[i]
    tab$typesim <- typesim[i]
    d <- rbind(d, tab)
}

d$prob <- as.numeric(gsub(" %", "", d$prob))


## Chargement des journées de championnat

doc <- htmlParse("http://www.maxifoot.fr/calendrier-ligue1.php", encoding="latin-1")
tableNodes <- getNodeSet(doc, "//table[@class='cd1']")
tables <- lapply(tableNodes, readHTMLTable)
for (i in 1:length(tables)) {
    names(tables[[i]]) <- c("eq.dom","eq.ext","score")
    tables[[i]]$journee <- i
}

results <- rbindlist(tables)

## Recodages

results <- within(results, {
    ## Matchs à venir
    score[score=="-"] <- NA
    score[!grepl("-", score)] <- NA
    ## Extraction score
    buts.dom <- gsub("-[0-9]+$","",score)
    buts.ext <- gsub("^[0-9]+-","",score)
    ## Recodage résultat
    result <- NA
    result[buts.dom > buts.ext] <- "dom"
    result[buts.dom < buts.ext] <- "ext"
    result[buts.dom == buts.ext] <- "nul"
    ## Recodage équipes
    dom <- as.character(eq.dom)
    ext <- as.character(eq.ext)
})

results <- results[,list(dom,ext,journee,result)]

classement.final <- data.frame(
    eq=c("Paris SG", "Monaco", "Lille", "St Etienne", "Lyon", "Marseille", 
"Bordeaux", "Lorient", "Toulouse", "Bastia", "Reims", "Rennes", 
"Nantes", "Evian TG", "Montpellier", "Guingamp", "Nice", "Sochaux", 
"Valenciennes", "AC Ajaccio"),
    classement=1:20)


## Fonction qui renvoie le classement d'une équipe à une journée particulière


classements <- rbindlist(lapply(20:38, function(i) {
        df <- calcule.points.journee(results,i)
        df$journee <- i
        df
    }))
classements <- as.data.frame(classements)
names(classements) <- c("eq", "points.reel", "classement.reel", "journee")

graph.equipe <- function(equipe, typesim="saison") {
    tmp <- d[d$typesim ==typesim & d$eq==equipe,]
    tmp.final <- as.numeric(classement.final %>% filter(eq==equipe) %>% select(classement))
    tmp$is.final <- tmp$classement == tmp.final
    tmp$journee <- as.numeric(tmp$journee)
    tmp$eq <- as.character(tmp$eq)
    tmp <- tmp %>% left_join(classements, by=c("journee", "eq"))
    tmp <- tmp %>% mutate(is.reel=classement==classement.reel)
    ggplot(data=tmp) + 
        geom_vline(xintercept=tmp.final, col="red") +
        geom_bar(aes(x=classement, y=prob, fill=is.reel), stat="identity") +
        facet_grid(journee~.) +
        scale_fill_manual(values=c("grey30","darkred"), guide="none")
}

graph.equipe("Rennes", "15j")
graph.equipe("Sochaux", "15j")
graph.equipe("Lyon", "15j")
graph.equipe("Marseille", "15j")
graph.equipe("Marseille", "saison")
graph.equipe("Montpellier", "15j")
graph.equipe("Montpellier", "saison")




```





